/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.*;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class CashierFrame extends javax.swing.JFrame {

    /**
     * Creates new form cashierFrame
     */
    int selectedCashId;
    int selectedCustomerId;
    int selectedOrderNum;
    double totalPrice;
    String SelPaymentType;
    DBAccess DBA;
    AppController AC;
    public CashierFrame() {
        initComponents();
        DBA = new DBAccess();
        AC = new AppController();
        setDefaultCloseOperation(CashierFrame.DISPOSE_ON_CLOSE);
        paymentTypeGroup.add(cashRadBut);
        paymentTypeGroup.add(creditRadBut);
        orderPanel.setVisible(false);
        cashPanel.setVisible(false);
        cashCombo.removeAllItems();
        cashCombo.addItem("Select a cashier id:");
        for (int i = 0; i < DBA.getAllCashIds(StartPageFrame.id).size(); i++) {
            cashCombo.addItem(DBA.getAllCashIds(StartPageFrame.id).get(i).toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paymentTypeGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        cashCombo = new javax.swing.JComboBox<>();
        selectBut = new javax.swing.JButton();
        cashPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        addCustomerBut = new javax.swing.JButton();
        addCusPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        lname = new javax.swing.JTextField();
        age = new javax.swing.JTextField();
        pnum = new javax.swing.JTextField();
        submitBut = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        custIdCombo = new javax.swing.JComboBox<>();
        productPanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        prodCombo = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        prName = new javax.swing.JTextField();
        prCat = new javax.swing.JTextField();
        prPrice = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        prAvQty = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        quantitySpinner = new javax.swing.JSpinner();
        selectCusBut = new javax.swing.JButton();
        proceedToOrderBut = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        orderNumber = new javax.swing.JTextField();
        orderPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cartArea = new javax.swing.JTextArea();
        cashIdLabel = new javax.swing.JLabel();
        brIdLabel = new javax.swing.JLabel();
        addOrderBut = new javax.swing.JButton();
        dateTime = new javax.swing.JLabel();
        totalToPay = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        cashRadBut = new javax.swing.JRadioButton();
        creditRadBut = new javax.swing.JRadioButton();
        proceedToCheckoutBut = new javax.swing.JButton();
        orderNumLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Cashier:");

        cashCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashComboActionPerformed(evt);
            }
        });

        selectBut.setText("Select");
        selectBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectButActionPerformed(evt);
            }
        });

        cashPanel.setBackground(new java.awt.Color(255, 153, 153));

        jLabel2.setText("Add customer if new:");

        addCustomerBut.setText("Add Customer");
        addCustomerBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCustomerButActionPerformed(evt);
            }
        });

        addCusPanel.setBackground(new java.awt.Color(204, 255, 204));

        jLabel3.setText("id:");

        jLabel4.setText("Name:");

        jLabel5.setText("Last Name:");

        jLabel6.setText("Age:");

        jLabel7.setText("Phone Number:");

        submitBut.setText("Submit");
        submitBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addCusPanelLayout = new javax.swing.GroupLayout(addCusPanel);
        addCusPanel.setLayout(addCusPanelLayout);
        addCusPanelLayout.setHorizontalGroup(
            addCusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addCusPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addCusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addCusPanelLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addCusPanelLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addCusPanelLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lname, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addCusPanelLayout.createSequentialGroup()
                        .addGroup(addCusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(addCusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pnum, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                            .addComponent(age)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addCusPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(submitBut, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        addCusPanelLayout.setVerticalGroup(
            addCusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addCusPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addCusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addCusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addCusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addCusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addCusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(pnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(submitBut)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel8.setText("Pick customer if exists:");

        custIdCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custIdComboActionPerformed(evt);
            }
        });

        productPanel.setBackground(new java.awt.Color(204, 255, 204));

        jLabel9.setText("Pick a product:");

        prodCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodComboActionPerformed(evt);
            }
        });

        jLabel10.setText("Product Name:");

        jLabel11.setText("Category:");

        jLabel12.setText("Price:");

        prName.setEditable(false);

        prCat.setEditable(false);

        prPrice.setEditable(false);

        jLabel13.setText("Available Quantity:");

        prAvQty.setEditable(false);

        addButton.setText("Add to cart");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        jLabel16.setText("Quantity:");

        quantitySpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        javax.swing.GroupLayout productPanelLayout = new javax.swing.GroupLayout(productPanel);
        productPanel.setLayout(productPanelLayout);
        productPanelLayout.setHorizontalGroup(
            productPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(productPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(productPanelLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(quantitySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, productPanelLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(53, 53, 53)
                        .addComponent(prodCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(productPanelLayout.createSequentialGroup()
                        .addGroup(productPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(productPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(prName)
                            .addComponent(prPrice)
                            .addComponent(prCat)
                            .addComponent(prAvQty, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE))))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        productPanelLayout.setVerticalGroup(
            productPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(productPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(prodCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(productPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(prName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(productPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(prCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(productPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(prPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(productPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(prAvQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(productPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addButton)
                    .addGroup(productPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16)
                        .addComponent(quantitySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        selectCusBut.setText("Select");
        selectCusBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectCusButActionPerformed(evt);
            }
        });

        proceedToOrderBut.setText("Proceed to order");
        proceedToOrderBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proceedToOrderButActionPerformed(evt);
            }
        });

        jLabel17.setText("Order Number:");

        javax.swing.GroupLayout cashPanelLayout = new javax.swing.GroupLayout(cashPanel);
        cashPanel.setLayout(cashPanelLayout);
        cashPanelLayout.setHorizontalGroup(
            cashPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cashPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(cashPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(cashPanelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(addCustomerBut, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(addCusPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(70, 70, 70)
                .addGroup(cashPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(cashPanelLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(custIdCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(productPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cashPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cashPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(selectCusBut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(proceedToOrderBut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(cashPanelLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(orderNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23))
        );
        cashPanelLayout.setVerticalGroup(
            cashPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cashPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cashPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(cashPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(addCustomerBut)
                        .addComponent(custIdCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(selectCusBut)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(cashPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addCusPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(productPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(cashPanelLayout.createSequentialGroup()
                        .addGroup(cashPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(orderNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(proceedToOrderBut)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        orderPanel.setBackground(new java.awt.Color(204, 204, 255));

        cartArea.setEditable(false);
        cartArea.setColumns(20);
        cartArea.setRows(5);
        jScrollPane1.setViewportView(cartArea);

        cashIdLabel.setText("Cashier id:");

        brIdLabel.setText("Branch id:");

        addOrderBut.setText("Add Order");
        addOrderBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addOrderButActionPerformed(evt);
            }
        });

        dateTime.setText("Date Time");

        jLabel14.setText("Total to pay:");

        jLabel15.setText("Payment Type:");

        cashRadBut.setText("Cash");

        creditRadBut.setText("Credit");

        proceedToCheckoutBut.setText("Proceed to checkout");
        proceedToCheckoutBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proceedToCheckoutButActionPerformed(evt);
            }
        });

        orderNumLabel.setText("Order number:");

        javax.swing.GroupLayout orderPanelLayout = new javax.swing.GroupLayout(orderPanel);
        orderPanel.setLayout(orderPanelLayout);
        orderPanelLayout.setHorizontalGroup(
            orderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orderPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(orderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(orderPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(orderPanelLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(orderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cashRadBut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(creditRadBut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(addOrderBut)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addGroup(orderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(totalToPay)
                            .addComponent(proceedToCheckoutBut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, orderPanelLayout.createSequentialGroup()
                        .addGroup(orderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(brIdLabel)
                            .addComponent(dateTime))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(orderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cashIdLabel)
                            .addComponent(orderNumLabel))
                        .addGap(41, 41, 41))))
        );
        orderPanelLayout.setVerticalGroup(
            orderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, orderPanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(orderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(brIdLabel)
                    .addComponent(orderNumLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(orderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateTime)
                    .addComponent(cashIdLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(orderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(orderPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(orderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cashRadBut)
                            .addComponent(jLabel15)
                            .addComponent(addOrderBut))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(creditRadBut))
                    .addGroup(orderPanelLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(orderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(totalToPay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(proceedToCheckoutBut)))
                .addGap(294, 294, 294))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(orderPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(cashCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(selectBut, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cashPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cashCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectBut))
                .addGap(7, 7, 7)
                .addComponent(cashPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(orderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 258, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addCustomerButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCustomerButActionPerformed
        addCusPanel.setVisible(true);
    }//GEN-LAST:event_addCustomerButActionPerformed

    private void selectButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectButActionPerformed
        String selectedCasId = cashCombo.getSelectedItem().toString();
        if (selectedCasId.equals("Select a cashier id:")) {
            JOptionPane.showMessageDialog(this, "Please select a cashier id", "No selected cashier id",
                    JOptionPane.ERROR_MESSAGE);
        } else {
            cashPanel.setVisible(true);
            addCusPanel.setVisible(false);
            productPanel.setVisible(false);
            selectedCashId = Integer.parseInt(selectedCasId);
            custIdCombo.removeAllItems();
            custIdCombo.addItem("Select a customer id:");
            for (int i = 0; i < DBA.getAllCusIds().size(); i++) {
                custIdCombo.addItem(DBA.getAllCusIds().get(i).toString());
            }
        }
    }//GEN-LAST:event_selectButActionPerformed

    private void submitButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButActionPerformed
        int CId = Integer.parseInt(id.getText());
        String cname = name.getText();
        String clname = lname.getText();
        int cAge = Integer.parseInt(age.getText());
        int CPNum = Integer.parseInt(pnum.getText());
        if (AC.checkCustomerId(CId)) {
            DBA.addCustomer(AC.addCustomer(CId, cAge, CPNum, cname, clname));
            JOptionPane.showMessageDialog(this, "Customer added", "Success",
                    JOptionPane.INFORMATION_MESSAGE);
            id.setText(null);
            name.setText(null);
            lname.setText(null);
            age.setText(null);
            pnum.setText(null);
            custIdCombo.removeAllItems();
            custIdCombo.addItem("Select a customer id:");
            for (int i = 0; i < DBA.getAllCusIds().size(); i++) {
                custIdCombo.addItem(DBA.getAllCusIds().get(i).toString());
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please select another id", "Customer id Already Exists",
                    JOptionPane.ERROR_MESSAGE);
            id.setText(null);
        }
    }//GEN-LAST:event_submitButActionPerformed

    private void custIdComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custIdComboActionPerformed

    }//GEN-LAST:event_custIdComboActionPerformed

    private void cashComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cashComboActionPerformed

    private void selectCusButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectCusButActionPerformed
        String selectedCusId = custIdCombo.getSelectedItem().toString();
        if (selectedCusId.equals("Select a customer id:")) {
            JOptionPane.showMessageDialog(this, "Please select a customer id", "No selected customer id",
                    JOptionPane.ERROR_MESSAGE);
        } else {
            productPanel.setVisible(true);
            selectedCustomerId = Integer.parseInt(selectedCusId);
            prodCombo.removeAllItems();
            prodCombo.addItem("Select a product code:");
            for (int i = 0; i < DBA.getAllProdCodes(StartPageFrame.id).size(); i++) {
                prodCombo.addItem(DBA.getAllProdCodes(StartPageFrame.id).get(i).toString());
            }
        }
    }//GEN-LAST:event_selectCusButActionPerformed

    private void prodComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodComboActionPerformed
        if (prodCombo.getSelectedItem().toString().equals("Select a product code:") == false) {
            ArrayList<String> AttOfProd = DBA.getProductAttributes(StartPageFrame.id,
                    Integer.parseInt(prodCombo.getSelectedItem().toString()));
            prName.setText(AttOfProd.get(0));
            prCat.setText(AttOfProd.get(1));
            prPrice.setText(AttOfProd.get(2) + " $");
            prAvQty.setText(AttOfProd.get(3));
        }
    }//GEN-LAST:event_prodComboActionPerformed

    private void proceedToOrderButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proceedToOrderButActionPerformed
        int orderNum = Integer.parseInt(orderNumber.getText());
        if (AC.checkOrderNum(orderNum)) {
            selectedOrderNum=orderNum;
            orderPanel.setVisible(true);
            Date D = new Date();
            Timestamp TS = new Timestamp(D.getTime());
            orderNumLabel.setText("Order number: "+selectedOrderNum);
            brIdLabel.setText("Branch id: " + StartPageFrame.id);
            cashIdLabel.setText("Cashier id: " + selectedCashId);
            dateTime.setText(TS.toString());
        } else {
            JOptionPane.showMessageDialog(this, "Please select another order number", "order "
                    + "number already exists", JOptionPane.ERROR_MESSAGE);
            orderNumber.setText(null);
        }
    }//GEN-LAST:event_proceedToOrderButActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        if(Integer.parseInt(quantitySpinner.getValue().toString())>Integer.parseInt(prAvQty.getText())==false){
        cartArea.append(prodCombo.getSelectedItem().toString() + "\t" + prName.getText() + "\t"
                + quantitySpinner.getValue().toString()+"\t"+prPrice.getText()+" /unit\n");
        AC.addToCart(selectedOrderNum, Integer.parseInt(prodCombo.getSelectedItem().toString())
                , Integer.parseInt(quantitySpinner.getValue().toString()));
        prodCombo.setSelectedItem("Select a product code:");
        prName.setText(null);
        prCat.setText(null);
        prPrice.setText(null);
        prAvQty.setText(null);
        quantitySpinner.setValue(1);
        }
        else JOptionPane.showMessageDialog(this, "Please select a lower quantity", "quantity "
                    + "required isn't available", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_addButtonActionPerformed

    private void addOrderButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addOrderButActionPerformed
        if(cashRadBut.isSelected())
            SelPaymentType="Cash";
        else if(creditRadBut.isSelected())
            SelPaymentType="Credit";
        DBA.addOrder(AC.addOrder(selectedOrderNum, selectedCustomerId, selectedCashId, StartPageFrame.id
                , dateTime.getText(), SelPaymentType));
        JOptionPane.showMessageDialog(this, "Order added", " Success", JOptionPane.INFORMATION_MESSAGE);
        for(int i=0;i<AC.getCart().size();i++){
            DBA.addIncludes(AC.getCart().get(i));
            DBA.updateProdQuantity(StartPageFrame.id, AC.getCart().get(i).getProd_code(), 
                    AC.getCart().get(i).getQtyBought());
        }
        ArrayList<Double> totPriceOfEachIncludes=DBA.getOrderTotalPriceOfEachInc(selectedOrderNum);
        for(int i=0;i<totPriceOfEachIncludes.size();i++)
            totalPrice+=totPriceOfEachIncludes.get(i);
        totalToPay.setText(String.valueOf(totalPrice)+" $");
    }//GEN-LAST:event_addOrderButActionPerformed

    private void proceedToCheckoutButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proceedToCheckoutButActionPerformed
        JOptionPane.showMessageDialog(this, "Your total to pay is "+totalToPay.getText(),
                " Thank you for your purchase", JOptionPane.INFORMATION_MESSAGE);
        prodCombo.setSelectedItem("Select a product code:");
        custIdCombo.setSelectedItem("Select a customer id:");
        prName.setText(null);
        prCat.setText(null);
        prPrice.setText(null);
        prAvQty.setText(null);
        quantitySpinner.setValue(1);
        orderNumber.setText(null);
        orderPanel.setVisible(false);
    }//GEN-LAST:event_proceedToCheckoutButActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CashierFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CashierFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CashierFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CashierFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CashierFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JPanel addCusPanel;
    private javax.swing.JButton addCustomerBut;
    private javax.swing.JButton addOrderBut;
    private javax.swing.JTextField age;
    private javax.swing.JLabel brIdLabel;
    private javax.swing.JTextArea cartArea;
    private javax.swing.JComboBox<String> cashCombo;
    private javax.swing.JLabel cashIdLabel;
    private javax.swing.JPanel cashPanel;
    private javax.swing.JRadioButton cashRadBut;
    private javax.swing.JRadioButton creditRadBut;
    private javax.swing.JComboBox<String> custIdCombo;
    private javax.swing.JLabel dateTime;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lname;
    private javax.swing.JTextField name;
    private javax.swing.JLabel orderNumLabel;
    private javax.swing.JTextField orderNumber;
    private javax.swing.JPanel orderPanel;
    private javax.swing.ButtonGroup paymentTypeGroup;
    private javax.swing.JTextField pnum;
    private javax.swing.JTextField prAvQty;
    private javax.swing.JTextField prCat;
    private javax.swing.JTextField prName;
    private javax.swing.JTextField prPrice;
    private javax.swing.JButton proceedToCheckoutBut;
    private javax.swing.JButton proceedToOrderBut;
    private javax.swing.JComboBox<String> prodCombo;
    private javax.swing.JPanel productPanel;
    private javax.swing.JSpinner quantitySpinner;
    private javax.swing.JButton selectBut;
    private javax.swing.JButton selectCusBut;
    private javax.swing.JButton submitBut;
    private javax.swing.JTextField totalToPay;
    // End of variables declaration//GEN-END:variables
}
