/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.DBAccess;
import java.util.ArrayList;

/**
 *
 * @author user
 */
public class HadiQueries extends javax.swing.JFrame {

    /**
     * Creates new form OurQueriesFrame
     */
    DBAccess DBA;
    public HadiQueries() {
        initComponents();
        setDefaultCloseOperation(HadiQueries.DISPOSE_ON_CLOSE);
        DBA=new DBAccess();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        task1Ans = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tasksArea = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        task2Ans = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        priceSpinner = new javax.swing.JSpinner();
        task3Ans = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        task4Ans = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Task 1: Find the total price of all the products that have the same manufacturer:");

        task1Ans.setText("Task 1 Answer");
        task1Ans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                task1AnsActionPerformed(evt);
            }
        });

        tasksArea.setEditable(false);
        tasksArea.setColumns(20);
        tasksArea.setRows(5);
        jScrollPane1.setViewportView(tasksArea);

        jLabel2.setText("Task 2: Find the name of the customers that buy alcohol and are under the age of 18:");

        task2Ans.setText("Task 2 Answer");
        task2Ans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                task2AnsActionPerformed(evt);
            }
        });

        jLabel3.setText("Task 3: Find the number of customers that buy products with price less than:");

        priceSpinner.setModel(new javax.swing.SpinnerNumberModel(1.0d, 1.0d, null, 1.0d));

        task3Ans.setText("Task 3 Answer");
        task3Ans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                task3AnsActionPerformed(evt);
            }
        });

        jLabel4.setText("Task 4: Find the name of the cashier that buys a product from any branch:");

        task4Ans.setText("Task 4 Answer");
        task4Ans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                task4AnsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(task1Ans, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(task2Ans, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(priceSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(task3Ans, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(task4Ans, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(task1Ans))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(task2Ans))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(priceSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(task3Ans))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(task4Ans))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void task1AnsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_task1AnsActionPerformed
        tasksArea.setText(null);
        ArrayList<String> manfAtt = DBA.Htask1();
        for (int i = 0; i < manfAtt.size();) {
            tasksArea.append(manfAtt.get(i++) + "\t");
            tasksArea.append(manfAtt.get(i++) + " $\n");
        }
    }//GEN-LAST:event_task1AnsActionPerformed

    private void task2AnsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_task2AnsActionPerformed
        tasksArea.setText(null);
        ArrayList<String> custAtt = DBA.Htask2();
        for (int i = 0; i < custAtt.size();) {
            tasksArea.append(custAtt.get(i++) + "\n");
        }
    }//GEN-LAST:event_task2AnsActionPerformed

    private void task3AnsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_task3AnsActionPerformed
        tasksArea.setText(null);
        double P=Double.parseDouble(priceSpinner.getValue().toString());
        int cCount=DBA.Htask3(P);
        if(cCount==0){
            tasksArea.setText("No orders include a product with a price less than "+P+" $ yet");
        }
        else tasksArea.setText(String.valueOf(cCount));
    }//GEN-LAST:event_task3AnsActionPerformed

    private void task4AnsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_task4AnsActionPerformed
        tasksArea.setText(null);
        ArrayList<String> cashAtt = DBA.Htask4();
        for (int i = 0; i < cashAtt.size();) {
            tasksArea.append(cashAtt.get(i++) + "\t");
            tasksArea.append(cashAtt.get(i++) + "\n");
        }
    }//GEN-LAST:event_task4AnsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HadiQueries.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HadiQueries.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HadiQueries.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HadiQueries.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HadiQueries().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner priceSpinner;
    private javax.swing.JButton task1Ans;
    private javax.swing.JButton task2Ans;
    private javax.swing.JButton task3Ans;
    private javax.swing.JButton task4Ans;
    private javax.swing.JTextArea tasksArea;
    // End of variables declaration//GEN-END:variables
}
