/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author user
 */
import control.*;
import javax.swing.JOptionPane;
public class ManagerFrame extends javax.swing.JFrame {

    /**
     * Creates new form ManagerFrame
     */
    DBAccess DBA;
    AppController AC;
    public ManagerFrame() {
        initComponents();
        addProdPanel.setVisible(false);
        addCashPanel.setVisible(false);
        setDefaultCloseOperation(ManagerFrame.DISPOSE_ON_CLOSE);
        int id=StartPageFrame.id;
        DBA = new DBAccess();
        AC=new AppController();
        welcomeLabel.setText("Welcome "+DBA.getBranchById(id).getM_fname()+" "+DBA.getBranchById(id).getM_lname());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcomeLabel = new javax.swing.JLabel();
        showAvProd = new javax.swing.JButton();
        addProdBut = new javax.swing.JButton();
        addProdPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        code = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        pName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        category = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        price = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        manf = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        prodSubmitBut = new javax.swing.JButton();
        qty = new javax.swing.JTextField();
        addCashBut = new javax.swing.JButton();
        showAvCash = new javax.swing.JButton();
        addCashPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cName = new javax.swing.JTextField();
        cLName = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        PNum = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        salary = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        joinYear = new javax.swing.JTextField();
        cashSubmitBut = new javax.swing.JButton();
        updateBut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        welcomeLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        welcomeLabel.setText("Welcome Mr. ");

        showAvProd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        showAvProd.setText("Show All Available Products In this Branch");
        showAvProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showAvProdActionPerformed(evt);
            }
        });

        addProdBut.setText("Add Product");
        addProdBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProdButActionPerformed(evt);
            }
        });

        addProdPanel.setBackground(new java.awt.Color(51, 255, 255));

        jLabel1.setText("Code:");

        jLabel2.setText("Name:");

        jLabel3.setText("Category:");

        jLabel4.setText("Price:");

        jLabel5.setText("Manufacturer:");

        jLabel6.setText("Quantity:");

        prodSubmitBut.setText("Submit");
        prodSubmitBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodSubmitButActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addProdPanelLayout = new javax.swing.GroupLayout(addProdPanel);
        addProdPanel.setLayout(addProdPanelLayout);
        addProdPanelLayout.setHorizontalGroup(
            addProdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addProdPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addProdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addProdPanelLayout.createSequentialGroup()
                        .addGroup(addProdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(30, 30, 30)
                        .addGroup(addProdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pName, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(category)
                            .addComponent(price)
                            .addComponent(code)))
                    .addGroup(addProdPanelLayout.createSequentialGroup()
                        .addGroup(addProdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(addProdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(prodSubmitBut, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                            .addComponent(manf)
                            .addComponent(qty))))
                .addContainerGap())
        );
        addProdPanelLayout.setVerticalGroup(
            addProdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addProdPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addProdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(code, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addProdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(pName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addProdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(category, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addProdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addProdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(manf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addProdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(qty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(prodSubmitBut)
                .addContainerGap())
        );

        addCashBut.setText("Add Cashier");
        addCashBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCashButActionPerformed(evt);
            }
        });

        showAvCash.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        showAvCash.setText("Show All Available Cashiers In this Branch");
        showAvCash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showAvCashActionPerformed(evt);
            }
        });

        addCashPanel.setBackground(new java.awt.Color(51, 255, 255));

        jLabel7.setText("id:");

        jLabel8.setText("Name:");

        jLabel9.setText("Last Name:");

        jLabel10.setText("Phone Number:");

        jLabel11.setText("Salary:");

        jLabel12.setText("Year Joined:");

        cashSubmitBut.setText("Submit");
        cashSubmitBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashSubmitButActionPerformed(evt);
            }
        });

        updateBut.setText("Update");
        updateBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addCashPanelLayout = new javax.swing.GroupLayout(addCashPanel);
        addCashPanel.setLayout(addCashPanelLayout);
        addCashPanelLayout.setHorizontalGroup(
            addCashPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addCashPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addCashPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addGap(21, 21, 21)
                .addGroup(addCashPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addCashPanelLayout.createSequentialGroup()
                        .addComponent(cashSubmitBut)
                        .addGap(18, 18, 18)
                        .addComponent(updateBut))
                    .addComponent(id)
                    .addComponent(cName)
                    .addComponent(cLName)
                    .addComponent(PNum)
                    .addComponent(joinYear)
                    .addComponent(salary))
                .addContainerGap())
        );
        addCashPanelLayout.setVerticalGroup(
            addCashPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addCashPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addCashPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addCashPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addCashPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cLName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addCashPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(PNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addCashPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(salary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addCashPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(joinYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(addCashPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cashSubmitBut)
                    .addComponent(updateBut))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(showAvCash, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showAvProd, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(welcomeLabel)
                        .addGap(463, 463, 463)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addProdBut)
                    .addComponent(addProdPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addCashBut)
                    .addComponent(addCashPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(97, 97, 97))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(welcomeLabel)
                .addGap(18, 18, 18)
                .addComponent(showAvProd, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(showAvCash, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addProdBut)
                    .addComponent(addCashBut))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addCashPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addProdPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showAvProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showAvProdActionPerformed
        AvailableProductsFrame APF=new AvailableProductsFrame();
        APF.setVisible(true);
    }//GEN-LAST:event_showAvProdActionPerformed

    private void addProdButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProdButActionPerformed
        addProdPanel.setVisible(true);
    }//GEN-LAST:event_addProdButActionPerformed

    private void prodSubmitButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodSubmitButActionPerformed
        int pCode=Integer.parseInt(code.getText());
        String name=pName.getText();
        String cat=category.getText();
        double pPrice=Double.parseDouble(price.getText());
        String pManf=manf.getText();
        int quantity=Integer.parseInt(qty.getText());
        if(AC.checkProductCode(StartPageFrame.id, pCode)){
            DBA.addProduct(AC.addProduct(pCode, name, cat, pPrice, pManf));
            DBA.addContain(AC.addContain(StartPageFrame.id, pCode, quantity));
            JOptionPane.showMessageDialog(this, "Product added", "Success", 
                    JOptionPane.INFORMATION_MESSAGE);
            code.setText(null);
            pName.setText(null);
            category.setText(null);
            price.setText(null);
            manf.setText(null);
            qty.setText(null);
        }
        else{
            JOptionPane.showMessageDialog(this, "Please select another code", "Product Code Already Exists", 
                    JOptionPane.ERROR_MESSAGE);
            code.setText(null);
        }
    }//GEN-LAST:event_prodSubmitButActionPerformed

    private void showAvCashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showAvCashActionPerformed
        AvailableCashiersFrame ACF=new AvailableCashiersFrame();
        ACF.setVisible(true);
    }//GEN-LAST:event_showAvCashActionPerformed

    private void addCashButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCashButActionPerformed
        addCashPanel.setVisible(true);
    }//GEN-LAST:event_addCashButActionPerformed

    private void cashSubmitButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashSubmitButActionPerformed
        int casId=Integer.parseInt(id.getText());
        String name=cName.getText();
        String lname=cLName.getText();
        int num=Integer.parseInt(PNum.getText());
        double cSalary=Double.parseDouble(salary.getText());
        int Year=Integer.parseInt(joinYear.getText());
        if(AC.checkCashierId(StartPageFrame.id, casId)){
            DBA.addCashier(AC.addCashier(casId, num, Year, StartPageFrame.id, cSalary, name, lname));
            JOptionPane.showMessageDialog(this, "Cashier added", "Success", 
                    JOptionPane.INFORMATION_MESSAGE);
            id.setText(null);
            cName.setText(null);
            cLName.setText(null);
            PNum.setText(null);
            salary.setText(null);
            joinYear.setText(null);
        }
        else{
            JOptionPane.showMessageDialog(this, "Please select another id", "Cashier Id Already Exists", 
                    JOptionPane.ERROR_MESSAGE);
            id.setText(null);
        }
    }//GEN-LAST:event_cashSubmitButActionPerformed

    private void updateButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButActionPerformed
        int casId=Integer.parseInt(id.getText());
        int num=Integer.parseInt(PNum.getText());
        double cSalary=Double.parseDouble(salary.getText());
        if(AC.checkCashierId(StartPageFrame.id, casId)==false){
            DBA.updateCashier(casId, cSalary, num);
            JOptionPane.showMessageDialog(this, "Cashier updated", "Success", 
                    JOptionPane.INFORMATION_MESSAGE);
            id.setText(null);
            cName.setText(null);
            cLName.setText(null);
            PNum.setText(null);
            salary.setText(null);
            joinYear.setText(null);
        }
        else{
            JOptionPane.showMessageDialog(this, "Please select an existing cashier id", "Cashier Id Doesn't Exist", 
                    JOptionPane.ERROR_MESSAGE);
            id.setText(null);
        }
    }//GEN-LAST:event_updateButActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagerFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField PNum;
    private javax.swing.JButton addCashBut;
    private javax.swing.JPanel addCashPanel;
    private javax.swing.JButton addProdBut;
    private javax.swing.JPanel addProdPanel;
    private javax.swing.JTextField cLName;
    private javax.swing.JTextField cName;
    private javax.swing.JButton cashSubmitBut;
    private javax.swing.JTextField category;
    private javax.swing.JTextField code;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField joinYear;
    private javax.swing.JTextField manf;
    private javax.swing.JTextField pName;
    private javax.swing.JTextField price;
    private javax.swing.JButton prodSubmitBut;
    private javax.swing.JTextField qty;
    private javax.swing.JTextField salary;
    private javax.swing.JButton showAvCash;
    private javax.swing.JButton showAvProd;
    private javax.swing.JButton updateBut;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
