/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.DBAccess;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class StartPageFrame extends javax.swing.JFrame {

    /**
     * Creates new form StartPageFrame
     */
    protected static int id;
    DBAccess DBA;
    public StartPageFrame() {
        initComponents();
        this.setTitle("Start Page");
        setDefaultCloseOperation(StartPageFrame.DISPOSE_ON_CLOSE);
        DBA = new DBAccess();
        brIdCombo.removeAllItems();
        brIdCombo.addItem("Select a branch id:");
        for (int i = 0; i < DBA.getAllBrIds().size(); i++) {
            brIdCombo.addItem(DBA.getAllBrIds().get(i).toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        managerBut = new javax.swing.JButton();
        brIdCombo = new javax.swing.JComboBox<>();
        cashierBut = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        ourQueriesCombo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Welcome To Our Supermarket");

        managerBut.setText("Manager");
        managerBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managerButActionPerformed(evt);
            }
        });

        brIdCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brIdComboActionPerformed(evt);
            }
        });

        cashierBut.setText("Cashier");
        cashierBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashierButActionPerformed(evt);
            }
        });

        jLabel2.setText("Our Queries:");

        ourQueriesCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Hadi's queries", "Fayez's queries", "Danielle's queries", "Toni's queries", "William's queries" }));
        ourQueriesCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ourQueriesComboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ourQueriesCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(192, 192, 192)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(managerBut)
                                .addComponent(cashierBut, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(brIdCombo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(managerBut)
                    .addComponent(brIdCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(cashierBut)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ourQueriesCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void managerButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managerButActionPerformed
        String selectedManId=brIdCombo.getSelectedItem().toString();
        if(selectedManId.equals("Select a branch id:"))
            JOptionPane.showMessageDialog(this, "Please select a branch id", "No selected branch id", 
                    JOptionPane.ERROR_MESSAGE);
        else{
            id=Integer.parseInt(brIdCombo.getSelectedItem().toString());
            ManagerFrame MF=new ManagerFrame();
            MF.setVisible(true);
        }
    }//GEN-LAST:event_managerButActionPerformed

    private void cashierButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashierButActionPerformed
        String selectedCasId=brIdCombo.getSelectedItem().toString();
        if(selectedCasId.equals("Select a branch id:"))
            JOptionPane.showMessageDialog(this, "Please select a branch id", "No selected branch id", 
                    JOptionPane.ERROR_MESSAGE);
        else{
            id=Integer.parseInt(brIdCombo.getSelectedItem().toString());
            CashierFrame CF=new CashierFrame();
            CF.setVisible(true);
        }
    }//GEN-LAST:event_cashierButActionPerformed

    private void ourQueriesComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ourQueriesComboActionPerformed
        String selectedQueries=ourQueriesCombo.getSelectedItem().toString();
        if(selectedQueries.equals("Hadi's queries")){
            HadiQueries HQ=new HadiQueries();
            HQ.setVisible(true);
        }
        else if(selectedQueries.equals("Fayez's queries")){
            FayezQueries FQ=new FayezQueries();
            FQ.setVisible(true);
        }
        else if(selectedQueries.equals("Danielle's queries")){
            DanielleQueries DQ=new DanielleQueries();
            DQ.setVisible(true);
        }
        else if(selectedQueries.equals("Toni's queries")){
            ToniQueries TQ=new ToniQueries();
            TQ.setVisible(true);
        }
        else if(selectedQueries.equals("William's queries")){
            WilliamQueries WQ=new WilliamQueries();
            WQ.setVisible(true);
        }
    }//GEN-LAST:event_ourQueriesComboActionPerformed

    private void brIdComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brIdComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_brIdComboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartPageFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartPageFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartPageFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartPageFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartPageFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> brIdCombo;
    private javax.swing.JButton cashierBut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton managerBut;
    private javax.swing.JComboBox<String> ourQueriesCombo;
    // End of variables declaration//GEN-END:variables
}
